Povezan ListingStock sa Exchange-om
RAF-SI-2023/Banka-1-Backend pull request #143
Opened 2024-03-25 14:59 UTC by LavTrgovcevic5320RN

2024-03-25 17:04 UTC, tismadusan567 commented
samo da proverim, exchange je vezan samo za stock, a ne za forex i ostale?

2024-03-25 17:06 UTC, LavTrgovcevic5320RN commented
Da, povezan je samo za stock

2024-03-25 18:48 UTC, ijevtic commented
a zasto je povezan samo za stock?

2024-03-25 18:53 UTC, ijevtic approved these changes

2024-03-25 18:53 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
ovo nije dobro, treba nam exchange za druge listinge

2024-03-25 18:53 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingStock.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
zasto ovo?

2024-03-25 18:53 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
drugi listinzi moraju da imaju ovo, cak i ako exchange ne moze da se poveze

2024-03-25 18:53 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/dtos/ListingBaseDto.java
> -    private String exchange;
ista prica

2024-03-25 18:56 UTC, ijevtic commented
pogresio sam, nije approve

2024-03-25 19:59 UTC, LavTrgovcevic5320RN commented
Exchange je povezan samo za stock jer ne postoji korelacija izmedju podataka koje se fetchuju sa apija za ostale listinge i exchange podataka tako da bih mogao da ih uvezem

2024-03-25 20:05 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingStock.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
Zato sto se desi kod Listing stocka da je isti exchange center obavio posao razmene deonica

2024-03-25 20:07 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingStock.java
> +    @ManyToOne(cascade = CascadeType.MERGE)
i samim time treba da bude isti exchange entitet, i onda ne dozvoljava CascadeType.ALL, nego mora da uradi merge

2024-03-25 20:14 UTC, ijevtic commented
ok, ali moras ostaviti exchange atribut u listing base, za druge listinge

2024-03-26 08:59 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
Hoces da ostavim da atribut bude String u ListingBase?

2024-03-26 09:09 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
Vratio sam sada Exchange u ListingBase, Listing Stock ce imati kljuceve (nece biti prazan) za Exchange dok ce kod ostalih biti null.

ListingForex
![image](https://github.com/RAF-SI-2023/Banka-1-Backend/assets/92125104/b77f03ae-3bff-46c9-8373-3339ca8f84a2)

ListingStock
![image](https://github.com/RAF-SI-2023/Banka-1-Backend/assets/92125104/2504cfde-1807-4e8e-8a00-5d447e339dd3)

2024-03-26 09:16 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/dtos/ListingBaseDto.java
> -    private String exchange;
Promenio sam

2024-03-26 14:23 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
Onda opet nemamo informaciju za Exchange-ve drugih listinga koji nisu stock? Bolje dodaj strani kljuc exchange iskljucio u ListingStock, a ostavi u listingBase-u String exchange

2024-03-26 14:27 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/model/ListingBase.java
> -    private String exchange;
Da, ne postoji korelacija izmedju ostalih listinga i exhange da bih mogao da ih povezem. Vazi, dodacu.

2024-03-26 15:24 UTC, tismadusan567 requested changes

2024-03-26 15:52 UTC, LavTrgovcevic5320RN commented on user-service/src/main/java/rs/edu/raf/banka1/mapper/ForeignCurrencyAccountMapper.java
> +    public String generateRandomNumber(int numOfDigits) {
Popravio sam da se broj racuna generise smislenije, ali je ta klasa sve jedno obrisana

2024-03-26 15:52 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/mapper/StockMapper.java
> +public class StockMapper extends ListingBaseMapper{
Uklonjeno, nepotrebno je bilo

2024-03-26 15:57 UTC, tismadusan567 commented on market-service/src/main/java/rs/edu/raf/banka1/mapper/StockMapper.java
> +public class StockMapper extends ListingBaseMapper{
vrv nisi pushovo izmene

2024-03-26 18:27 UTC, LavTrgovcevic5320RN commented on market-service/src/main/java/rs/edu/raf/banka1/mapper/StockMapper.java
> +public class StockMapper extends ListingBaseMapper{
Pushovao sam sada

2024-03-26 19:24 UTC, LavTrgovcevic5320RN commented
Vratio sam exchange atribut u listing base, za druge listinge

2024-03-26 19:47 UTC, merged