Admin edit customer
RAF-SI-2023/Banka-1-Backend pull request #144
Opened 2024-03-25 19:25 UTC by cvele0

2024-03-25 21:55 UTC, ijevtic commented
testovi?

2024-03-25 23:49 UTC, cvele0 commented
Dodao sam testove i preimenovao metode.

2024-03-26 11:36 UTC, savatarko requested changes
testovi su okej, ali je sklonjena kolona koja je potrebna po specifikaciji

2024-03-26 11:36 UTC, savatarko commented on user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
zasto je ovo zakomentarisano?

2024-03-26 12:05 UTC, cvele0 commented on user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
Zato sto je suvisno, to se cuva u jmbg

2024-03-26 12:11 UTC, cvele0 commented on user-service/src/main/java/rs/edu/raf/banka1/model/Customer.java
Nisam nista sklanjao, ne znam o cemu pricas

2024-03-26 15:32 UTC, tismadusan567 commented on user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
> +        createRandomUsers();
Zar nije seed za stvari koji nam zapravo trebaju u bazi, kolko vidim ovaj korisnik se samo pravi ovde radi testiranja? @ijevtic

2024-03-26 15:36 UTC, tismadusan567 commented on user-service/src/main/java/rs/edu/raf/banka1/services/CustomerService.java
> +    boolean editUser(EditCustomerRequest editCustomerRequest);
trebalo bi da se zove editCustomer

2024-03-26 15:50 UTC, cvele0 commented
Popravljeno

2024-03-26 15:53 UTC, cvele0 commented on user-service/src/main/java/rs/edu/raf/banka1/services/CustomerService.java
> +    boolean editUser(EditCustomerRequest editCustomerRequest);
Popravljeno

2024-03-26 19:48 UTC, merged