Sprint 3 andrejadikic
RAF-SI-2023/Banka-1-Backend pull request #147
Opened 2024-03-25 22:43 UTC by andrejadikic

2024-03-25 23:57 UTC, ijevtic commented on user-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
> +            "manage_loans", "manage_loan_requests"
bolje da je unifikovano, ako smo krenuli sa camelCase, da nastavimo tako

2024-03-25 23:57 UTC, ijevtic commented on user-service/src/main/java/rs/edu/raf/banka1/dtos/LoanDto.java
> +@Data
@savatarko je rekao da mu prilikom testova prave problem anotacije Data, bolje da se razdvoji na @ Getter i Setter.

2024-03-25 23:57 UTC, ijevtic commented on user-service/src/main/java/rs/edu/raf/banka1/services/LoanRequestServiceImpl.java
> +    public boolean changeRequestStatus(Long id, LoanRequestStatus loanRequestStatus) {
ovo svakako uvek vraca true, moze da bude i void, nit

2024-03-26 21:55 UTC, andrejadikic commented on user-service/src/main/java/rs/edu/raf/banka1/services/LoanRequestServiceImpl.java
> +    public boolean changeRequestStatus(Long id, LoanRequestStatus loanRequestStatus) {
promenila

2024-03-26 22:25 UTC, cvele0 commented
Pregazila si moje izmene u bootstrapu, nisi dobro merge odradila

2024-03-26 22:28 UTC, andrejadikic commented
> Pregazila si moje izmene u bootstrapu, nisi dobro merge odradila

samo sam prihvatila sve sa sprinta 3 i dodala manageLoans i request i final

2024-03-27 11:14 UTC, savatarko requested changes
skloniti verify provere za mappere, nepotrebno i cini testove lomljivijim. treba raditi verify samo za stvari koje mogu da promene stanje (npr cuvanje u bazu)

2024-03-27 22:02 UTC, merged