Sprint 4
RAF-SI-2023/Banka-1-Backend pull request #186
Opened 2024-04-03 18:00 UTC by MarkoNik

https://github.com/RAF-SI-2023/Banka-1-Backend/issues/162

Prvi pull request vezan za ovaj tiket, u kom je napravljen novi servis "fetching service", gde je kopirana logika za api fetchovanje i web scraping iz market servisa. Za sada, nije napravljena nikakva izmena u market servisu, ali ce u sledecem pull requestu biti izbrisana logika za fetchovanje iz market servisa.

2024-04-03 18:37 UTC, MarkoNik commented
nisam menjao logiku, malo sam refaktorisao i u sustini deluje da radi fino. u svakom slucaju nece sjebati nista jer ne menja logiku postojecih servisa

2024-04-03 18:37 UTC, MarkoNik commented
testovi prolaze

2024-04-03 19:31 UTC, Kovelja009 commented
Super.

2024-04-03 19:31 UTC, Kovelja009 approved these changes
nadam se da je okej i da ništa novo nisi morao da dodaješ u logiku i da ovo radi.

2024-04-03 22:22 UTC, ijevtic commented
ja se stvarno nadam da ovo radi, nzm kako da gledam pr ovde iskreno

2024-04-03 22:25 UTC, ijevtic requested changes

2024-04-03 22:25 UTC, ijevtic commented on fetching-service/fetching-service/src/main/resources/logs/log_0.txt
> +2024-04-03 20:00:17     ForexServiceImpl.getUpdatedForex()     INFO: BaseCurrency: null, QuoteCurrency: null are not available on the alphavantage API
Skloni logove sa gita, dodaj u .gitignore.

2024-04-03 22:25 UTC, ijevtic commented on fetching-service/mvnw
> +    echo "Investigate or delete $wrapperJarPath to attempt a clean download." >&2
sta je ovo tacno? Jel ovo ide u .gitignore?

2024-04-03 22:25 UTC, ijevtic commented on fetching-service/src/main/resources/application.properties
> +
nemoj ovo na git, napravi example

2024-04-03 22:25 UTC, ijevtic commented on fetching-service/src/main/resources/application.properties
> +
vidim da ima example, onda samo skloni ovo

2024-04-04 01:52 UTC, ijevtic approved these changes

2024-04-04 01:52 UTC, merged