Sprint 1
RAF-SI-2023/Banka-1-Backend pull request #36
Opened 2024-03-12 22:45 UTC by LavTrgovcevic5320RN

Uradjen Currency fetch

2024-03-13 12:14 UTC, ijevtic requested changes

2024-03-13 12:14 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/entities/Currency.java
> +import lombok.*;
nije pokrenut linter

2024-03-13 12:14 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/entities/ExampleModel.java
> +package rs.edu.raf.banka1.model.entities;
zasto novi paket? Mislim da je lakse da sve ide u /model

2024-03-13 12:14 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
> +    public Map<String, String> loadCurrencies() {
malo mi je neuobicajeno da se vrednosti salju u mapi. Cini mi se da bi lakse bilo slati Listu parova, ili napraviti dto strukturu koja sadrzi kod i ime

2024-03-13 12:14 UTC, ijevtic commented on market-service/src/main/resources/examples/application.properties.example
zasto je ovo obrisano?

2024-03-13 12:14 UTC, ijevtic commented
imas konflikte, kad resis ove komentare samo merguje sa sprint granom ponovo

2024-03-13 18:21 UTC, LavTrgovcevic5320RN commented on market-service/src/main/resources/examples/application.properties.example
Samo sam ga pomerio u resources folder i sklonio .example ekstenziju kako bi ga spring pronasao i da bih mogao da koristim bazu.

2024-03-13 18:23 UTC, ijevtic commented on market-service/src/main/resources/examples/application.properties.example
application.properties ide u .gitignore, treba da ga napravis po uzoru na application.properties.example. On stoji kao primer kako treba da izgleda application.properties, ne zelimo da ga brisemo

2024-03-14 08:43 UTC, LavTrgovcevic5320RN commented
Ispravljeno sve i koriscen linter

2024-03-14 16:50 UTC, ijevtic approved these changes

2024-03-14 16:50 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/controller/CurrencyController.java
> +    @GetMapping(value = "/{id}")
fali @Operation za swagger

2024-03-14 16:50 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/entities/Currency.java
> +import jakarta.persistence.*;
nije pokrenut linter

2024-03-14 16:50 UTC, merged