B2 - Stock service - Exchange
RAF-SI-2023/Banka-1-Backend pull request #74
Opened 2024-03-17 17:54 UTC by tismadusan567

2024-03-17 18:04 UTC, ijevtic commented
gde su testovi?

2024-03-17 18:08 UTC, ijevtic requested changes

2024-03-17 18:08 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/services/ExchangeServiceImpl.java
> +    private static class BusinessHoursDto {
bolje da ga ekstraktujes u zasebni fajl

2024-03-17 18:08 UTC, ijevtic commented on scripts/generate_country_timezone_offsets/generate_country_timezone_offsets.py
> +    url = "http://api.timezonedb.com/v2.1/list-time-zone"
znaci odvojeno se pokrene skripta koja generise csv?

2024-03-17 18:08 UTC, ijevtic commented on market-service/src/main/resources/working_hours_and_holidays_for_exchanges.json
mislim da je bolje da ovi generisani fajllovi idu u .gitignore, pa da se pokrene neka skripta koja radi te inicijalne fetch-eve, i da se napise u readme.

2024-03-17 18:10 UTC, tismadusan567 commented on market-service/src/main/java/rs/edu/raf/banka1/model/entities/Country.java
> +    private Date closeTime;
Unix timestamp predstavlja ceo datum, ovde koristim Data samo za sate minute i sekunde

2024-03-17 18:14 UTC, tismadusan567 commented on scripts/generate_country_timezone_offsets/generate_country_timezone_offsets.py
> +    url = "http://api.timezonedb.com/v2.1/list-time-zone"
csv nema skriptu, vec postoji na netu

2024-03-17 18:16 UTC, tismadusan567 commented
> gde su testovi?

Ubacicu

2024-03-17 18:17 UTC, tismadusan567 commented on market-service/src/main/java/rs/edu/raf/banka1/services/ExchangeServiceImpl.java
> +    private static class BusinessHoursDto {
Done

2024-03-17 18:19 UTC, ijevtic commented on scripts/generate_country_timezone_offsets/generate_country_timezone_offsets.py
> +    url = "http://api.timezonedb.com/v2.1/list-time-zone"
mislim na ove podatke koji se fetchuju

2024-03-17 18:35 UTC, tismadusan567 commented on scripts/generate_country_timezone_offsets/generate_country_timezone_offsets.py
> +    url = "http://api.timezonedb.com/v2.1/list-time-zone"
da odvojeno se pokrene

2024-03-18 10:30 UTC, savatarko approved these changes
testovi okej

2024-03-18 13:27 UTC, merged