Options fetch
RAF-SI-2023/Banka-1-Backend pull request #92
Opened 2024-03-18 22:52 UTC by jsimc

2024-03-18 23:25 UTC, ijevtic commented
konflikti

2024-03-19 12:26 UTC, ijevtic requested changes

2024-03-19 12:26 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/OptionsModel.java
> +    private double strikePrice;
Bolje koristiti klasne umesto primitivnih tipova, potencijalno mesto za cudne errore

2024-03-19 12:26 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/model/dtos/OptionsDto.java
> +    private OptionType optionType;
ovo ce vratiti broj 0,1,2 posto je Enum, mozda bolje string?

2024-03-19 12:26 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
> +    private static String cookie = null;
zasto static?

2024-03-19 12:26 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
> +                //  this should be done async! Uncomment when done! Or uncomment to see that it works but slowly!
todo

2024-03-19 12:26 UTC, ijevtic commented
jel se nista ne cuva u bazi?

2024-03-19 16:20 UTC, janamarkovic12621rn commented
> jel se nista ne cuva u bazi?

sta ce nam podaci?

2024-03-19 16:33 UTC, ijevtic commented
> > jel se nista ne cuva u bazi?
> 
> sta ce nam podaci?

pa ako vise puta pozovemo opcije za isti listing, da ne radi fetch stalno?

2024-03-19 23:47 UTC, ijevtic approved these changes

2024-03-19 23:47 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/services/OptionsServiceImpl.java
> +                return null;
mislim da je bolja praksa da se posalje prazan niz, umesto null.

2024-03-19 23:47 UTC, ijevtic requested changes

2024-03-19 23:47 UTC, ijevtic commented on market-service/src/main/java/rs/edu/raf/banka1/bootstrap/BootstrapData.java
> +import rs.edu.raf.banka1.services.OptionsService;
nesto sam se zajebao

2024-03-20 09:40 UTC, savatarko approved these changes
testovi ok

2024-03-20 09:40 UTC, merged